[features]
seeds = false
skip-lint = false
[programs.devnet]
agreement_program = "FqaqjUy4n1ysFZi6Jr7XeGDzu5f1gt7a85mVLGjP1cRX"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/Users/nomadbitcoin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
