[features]
seeds = false
skip-lint = false
[programs.localnet]
agreement_program = "FqaqjUy4n1ysFZi6Jr7XeGDzu5f1gt7a85mVLGjP1cRX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/brunobarros/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
